/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.supermarket.view;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import lk.supermarket.model.Customer;
import lk.supermarket.controller.CustomerController;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Gebruiker
 */
public class AddNewCustomer extends javax.swing.JFrame {

    /**
     * Creates new form AddNewCustomer
     */
    public AddNewCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        postalCodeTxt = new javax.swing.JTextField();
        custTitleTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        custNameTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        custAddressTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cityTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        provinceTxt = new javax.swing.JTextField();
        custIDTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        addCustomerBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Super Market");
        setIconImage( Toolkit.getDefaultToolkit().getImage("U:\\Document\\ijse\\ASSINGMENT\\#19\\supermarket.png") );
        setLocation(new java.awt.Point(580, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 404, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add New Customer");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 49));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Customer Title");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 100, -1, -1));
        getContentPane().add(postalCodeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 321, 220, -1));
        getContentPane().add(custTitleTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 97, 220, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Customer Name");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 147, -1, -1));
        getContentPane().add(custNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 144, 220, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Customer Address");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 187, -1, -1));
        getContentPane().add(custAddressTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 184, 220, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("City");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 235, 41, -1));
        getContentPane().add(cityTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 232, 220, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Province");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 280, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Customer ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 59, -1, -1));

        provinceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provinceTxtActionPerformed(evt);
            }
        });
        getContentPane().add(provinceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 277, 220, -1));

        custIDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custIDTxtActionPerformed(evt);
            }
        });
        getContentPane().add(custIDTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 56, 220, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Postal Code");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 324, -1, -1));

        addCustomerBtn.setBackground(new java.awt.Color(0, 0, 0));
        addCustomerBtn.setForeground(new java.awt.Color(255, 255, 255));
        addCustomerBtn.setText("Add New Customer");
        addCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addCustomerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 361, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supermarket/newpackage/backgroung.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, -7, 490, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void custIDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custIDTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custIDTxtActionPerformed

    private void provinceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provinceTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_provinceTxtActionPerformed

    private void addCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerBtnActionPerformed
        String CustID=custIDTxt.getText();
        String CustTitle=custTitleTxt.getText();
        String CustName=custNameTxt.getText();
        String CustAddress=custAddressTxt.getText();
        String City=cityTxt.getText();
        String Province=provinceTxt.getText();
        String PostalCode=postalCodeTxt.getText();
        Customer customer=new Customer(CustID,CustTitle,CustName,CustAddress,City,Province,PostalCode);
        try {
            boolean isAdded = CustomerController.addCustomer(customer);
            if (isAdded) {
                JOptionPane.showMessageDialog(this, "Added Success");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Driver not found");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_addCustomerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomerBtn;
    private javax.swing.JTextField cityTxt;
    private javax.swing.JTextField custAddressTxt;
    private javax.swing.JTextField custIDTxt;
    private javax.swing.JTextField custNameTxt;
    private javax.swing.JTextField custTitleTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField postalCodeTxt;
    private javax.swing.JTextField provinceTxt;
    // End of variables declaration//GEN-END:variables
}
