/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.supermarket.view;

import lk.supermarket.model.Orders;
import lk.supermarket.model.Customer;
import lk.supermarket.controller.CustomerController;
import lk.supermarket.controller.OrderController;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.supermarket.controller.ItemController;
import lk.supermarket.model.Item;
import lk.supermarket.model.OrderDetails;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Gebruiker
 */
public class Cashier extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Cashier() {
        initComponents();
        genarateOrderDate();
        genarateOrderId();
        loadAllCustomers();
        loadAllItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addOrderBtn = new javax.swing.JButton();
        newCustomerBtn = new javax.swing.JButton();
        orderDateLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        orderIDLbl = new javax.swing.JLabel();
        cmbCustomerId = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        lblCustomerName = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbItemCode = new javax.swing.JComboBox<>();
        lblDescription = new javax.swing.JLabel();
        lblUnitPrice = new javax.swing.JLabel();
        lblQtyOnHand = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lblPackSize = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderDetailsTbl = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Super Market");
        setIconImage( Toolkit.getDefaultToolkit().getImage("U:\\Document\\ijse\\ASSINGMENT\\#19\\supermarket.png") );
        setLocation(new java.awt.Point(300, 150));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cashier Control Area");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 958, 33));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(883, 586, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Order Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(757, 46, -1, 26));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Customer ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 134, -1, -1));

        addOrderBtn.setBackground(new java.awt.Color(0, 0, 0));
        addOrderBtn.setForeground(new java.awt.Color(255, 255, 255));
        addOrderBtn.setText("Place Order");
        addOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrderBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addOrderBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(777, 586, -1, -1));

        newCustomerBtn.setBackground(new java.awt.Color(51, 51, 51));
        newCustomerBtn.setForeground(new java.awt.Color(255, 255, 255));
        newCustomerBtn.setText("Add New");
        newCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCustomerBtnActionPerformed(evt);
            }
        });
        getContentPane().add(newCustomerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 130, -1, -1));

        orderDateLbl.setForeground(new java.awt.Color(255, 255, 255));
        orderDateLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(orderDateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(832, 46, 114, 27));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Order ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 71, 72, 28));

        orderIDLbl.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(orderIDLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 71, 95, 28));

        cmbCustomerId.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        cmbCustomerId.setForeground(new java.awt.Color(255, 255, 255));
        cmbCustomerId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCustomerIdItemStateChanged(evt);
            }
        });
        cmbCustomerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCustomerIdActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 125, 120, -1));

        jLabel5.setText("Customer Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(672, 134, -1, -1));

        lblCustomerName.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        lblCustomerName.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lblCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(791, 125, 155, 30));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Item Code");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 202, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Description");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 202, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Unit Price");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 202, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Qty On Hand");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(639, 202, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Qty");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(804, 202, -1, -1));

        cmbItemCode.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        cmbItemCode.setForeground(new java.awt.Color(255, 255, 255));
        cmbItemCode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbItemCodeItemStateChanged(evt);
            }
        });
        getContentPane().add(cmbItemCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 236, 103, -1));

        lblDescription.setBackground(new java.awt.Color(0, 0, 0));
        lblDescription.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        lblDescription.setForeground(new java.awt.Color(3, 30, 159));
        lblDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDescription.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 236, 193, 30));

        lblUnitPrice.setBackground(new java.awt.Color(0, 0, 153));
        lblUnitPrice.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        lblUnitPrice.setForeground(new java.awt.Color(0, 0, 153));
        lblUnitPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUnitPrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblUnitPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 236, 136, 30));

        lblQtyOnHand.setBackground(new java.awt.Color(0, 0, 0));
        lblQtyOnHand.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        lblQtyOnHand.setForeground(new java.awt.Color(255, 255, 0));
        lblQtyOnHand.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQtyOnHand.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblQtyOnHand, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 236, 117, 30));

        txtQty.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        txtQty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyActionPerformed(evt);
            }
        });
        txtQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQtyKeyPressed(evt);
            }
        });
        getContentPane().add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 236, 178, 33));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Pack Size");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 202, -1, -1));

        lblPackSize.setBackground(new java.awt.Color(0, 0, 0));
        lblPackSize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPackSize.setForeground(new java.awt.Color(255, 255, 0));
        lblPackSize.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblPackSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 236, 118, 30));

        jLabel16.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("Total : ");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 553, -1, -1));

        lblTotal.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 557, 166, 28));

        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        orderDetailsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Description", "Pack Size", "Unit Price", "Qty", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orderDetailsTbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 287, 926, 228));

        btnAdd.setBackground(new java.awt.Color(0, 0, 0));
        btnAdd.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 515, 106, -1));

        btnRemove.setBackground(new java.awt.Color(0, 0, 0));
        btnRemove.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        btnRemove.setForeground(new java.awt.Color(255, 255, 255));
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 515, 138, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Main Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 586, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(":");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 72, 13, 24));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supermarket/newpackage/backgroung.jpg"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void genarateOrderDate() {
        LocalDate date = LocalDate.now(); //Since JDK1.8
       orderDateLbl.setText(date.toString());
     
    }
     private void genarateOrderId() {
        try {
            int lastOrderId = OrderController.getLastOrderId();
            if (lastOrderId != 0) {
                lastOrderId = (lastOrderId + 1);
                orderIDLbl.setText(lastOrderId+"");
            } else {
                orderIDLbl.setText(1+"");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Cashier.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Cashier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void loadAllCustomers() {
        try {
            ArrayList<Customer> customers = CustomerController.getAllCustomers();
            for (Customer c : customers) {
               cmbCustomerId.addItem(c.getCustID());
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Cashier.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Cashier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void loadAllItems() {
        try {
            ArrayList<Item> items = ItemController.loadAllItems();
            for (Item i : items) {
                cmbItemCode.addItem(i.getItemCode());
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Cashier.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Cashier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private int isAlreadyExist(String itemCode) {
        DefaultTableModel dtm = (DefaultTableModel) orderDetailsTbl.getModel();

        for (int i = 0; i < orderDetailsTbl.getRowCount(); i++) {
            String code = (String) dtm.getValueAt(i, 0);

            if (code.equals(itemCode)) {
                return i;
            }
        }
        return -1;
    }
    
    private void calculateTotal() {
        DefaultTableModel dtm = (DefaultTableModel) orderDetailsTbl.getModel();

        double total = 0;

        for (int i = 0; i < dtm.getRowCount(); i++) {
            total += (double) dtm.getValueAt(i, 5);
        }
        lblTotal.setText(total + "");
    }
    private void addOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrderBtnActionPerformed
        int OrderId = Integer.parseInt(orderIDLbl.getText());
        String CustID = cmbCustomerId.getSelectedItem().toString();
        String OrderDate = orderDateLbl.getText();
        DefaultTableModel dtm = (DefaultTableModel) orderDetailsTbl.getModel();
        ArrayList<OrderDetails> orderDetailList = new ArrayList<>();
        for (int i = 0; i < dtm.getRowCount(); i++) {
            String itemCode = (String) dtm.getValueAt(i, 0);
            double unitPrice = (double) dtm.getValueAt(i, 3);
            int qty = (int) dtm.getValueAt(i, 4);
            OrderDetails orderDetails = new OrderDetails(OrderId,itemCode,qty);
            orderDetailList.add(orderDetails);
        }
        Orders orders = new Orders(OrderId, OrderDate, CustID, orderDetailList);

        try {
            boolean isAdded = OrderController.addOrder(orders);
            if (isAdded) {
                JOptionPane.showMessageDialog(this, "Added Success");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Cashier.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Cashier.class.getName()).log(Level.SEVERE, null, ex);
        }
//int OrderID=Integer.parseInt(orderIDTxt.getText());
        /*String OrderDate=orderDateLbl.getText();
        String CustID=cmbCustomerId.getText();
         
        Orders orders=new Orders(OrderDate,CustID);
        try {
            boolean isAdded = OrderController.addOrders(orders);
            if (isAdded) {
                JOptionPane.showMessageDialog(this, "Added Success");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Driver not found");
        } */// TODO add your handling code here:
    }//GEN-LAST:event_addOrderBtnActionPerformed

    private void newCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCustomerBtnActionPerformed
         new AddNewCustomer().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_newCustomerBtnActionPerformed

    private void cmbCustomerIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCustomerIdItemStateChanged
        try {
            String customerId = cmbCustomerId.getSelectedItem().toString();
            Customer customer = CustomerController.searchCustomer(customerId);
            lblCustomerName.setText(customer.getCustName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Cashier.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Cashier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbCustomerIdItemStateChanged

    private void cmbCustomerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCustomerIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCustomerIdActionPerformed

    private void cmbItemCodeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbItemCodeItemStateChanged
        try {
            String itemCode = cmbItemCode.getSelectedItem().toString();
            Item item = ItemController.searchItem(itemCode);
            lblDescription.setText(item.getDiscription());
            lblPackSize.setText(item.getPackSize());
            lblUnitPrice.setText(item.getUnitPrice() + "");
            lblQtyOnHand.setText(item.getQtyOnHand() + "");

            txtQty.requestFocus();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Cashier.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Cashier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbItemCodeItemStateChanged

    private void txtQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyActionPerformed

    }//GEN-LAST:event_txtQtyActionPerformed

    private void txtQtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyPressed
            
    }//GEN-LAST:event_txtQtyKeyPressed
        
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) orderDetailsTbl.getModel();

        int qty = Integer.parseInt(txtQty.getText());
        double unitPrice = Double.parseDouble(lblUnitPrice.getText());
        double total = unitPrice * qty;

        int row = isAlreadyExist(cmbItemCode.getSelectedItem().toString());

        if (row == -1) {
            Object[] rowData = {cmbItemCode.getSelectedItem().toString(), lblDescription.getText(),lblPackSize.getText(), unitPrice,qty,total};
            dtm.addRow(rowData);
        } else {
            qty += (int) dtm.getValueAt(row, 4);
            total = qty * unitPrice;

            orderDetailsTbl.setValueAt(qty, row, 4);
            orderDetailsTbl.setValueAt(total, row, 6);
        }

        cmbItemCode.requestFocus();
        calculateTotal();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        int selectedRow =orderDetailsTbl.getSelectedRow();

        if (selectedRow == -1) {
            return;
        }
        DefaultTableModel dtm = (DefaultTableModel)orderDetailsTbl.getModel();
        dtm.removeRow(selectedRow);

        calculateTotal();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new SuperMarketMain().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**Integer.parseInt
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cashier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOrderBtn;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox<String> cmbCustomerId;
    private javax.swing.JComboBox<String> cmbItemCode;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblPackSize;
    private javax.swing.JLabel lblQtyOnHand;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblUnitPrice;
    private javax.swing.JButton newCustomerBtn;
    private javax.swing.JLabel orderDateLbl;
    private javax.swing.JTable orderDetailsTbl;
    private javax.swing.JLabel orderIDLbl;
    private javax.swing.JTextField txtQty;
    // End of variables declaration//GEN-END:variables
}
